apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperpub.fullname" . }}
  labels:
    {{- include "paperpub.labels" . | nindent 4 }}
  {{- if .Values.enableDownscaler }}
  annotations:
    downscaler/exclude: "false"
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "paperpub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paperpub.selectorLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.enableMonitor }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
            {{- if .Values.enableMonitor }}
            - name: metrics
              containerPort: 9091
              protocol: TCP
            {{- end }}
          env:
            - name: env
              value: {{ .Values.envProfile | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "paperpub.fullname" . }}-config
            - secretRef:
                name: {{ include "paperpub.fullname" . }}-secret
          {{- if .Values.enableHealthCheck }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-data" (include "paperpub.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
