{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: paperpub-mysql-secret
  labels:
    {{- include "paperpub.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
{{- end }}
